name: building

on: push

jobs:        
  building:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      
      - name: Install gcc env
        run: |
          sudo apt update
          sudo apt install gcc g++
        shell: bash
    
      - name: cmake project
        run: |
          cd ${{github.workspace}}
          mkdir build
          cd build
          cmake ../
          make

