name: build-and-test

on: push
    
env:
  CC: gcc-4.9
  CXX: g++-4.9
  secret_account: ${{ secrets.DOCKER_USERNAME }}

jobs:      
# Testing Cache Only
  test-abc:
    runs-on: ubuntu-20.04
    services:
      dtc:
        image: ${{github.path}}
        ports:
          - 20015:20015
        volumes:
          - /usr/local/etc:/usr/local/dtc/conf/
        options: --name dtc
        env:
          DTC_BIN: agent-watchdog
          DTC_ARGV: -c
    steps:
      - uses: actions/checkout@v3
      
      - name: Install python dependency
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pymysql

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Copy conf files.
        run: |
          cd ${{github.workspace}}   
          sudo cp -f conf/log4cplus.conf /usr/local/etc/ 
          sudo cp -f conf/log4cplus-hwc.conf /usr/local/etc/ 
          sudo cp -f conf/log4cplus-wd.conf /usr/local/etc/
          sudo cp -f conf/log4cplus-async.conf /usr/local/etc/
          sudo cp -f conf/log4cplus-agent.conf /usr/local/etc/
          sudo cp -f conf/log4cplus-life.conf /usr/local/etc/
          sudo cp -f dockerfiles/devel/dtc.cacheonly.yaml /usr/local/etc/dtc.yaml

      - name: Run Testing Cases
        run: |
          sleep 5s
          docker ps -a
          docker logs dtc
          cd ${{github.workspace}}/tests
          pytest test_dtcd_cache_only.py     
          
