name: build-and-test

on: push
    
env:
  CC: gcc-4.9
  CXX: g++-4.9
  secret_account: ${{ secrets.DOCKER_USERNAME }}
  sec: hello
  MAVEN_VERSION: dockerpath:abc

jobs:      
  prepare-image:
    runs-on: ubuntu-20.04
    outputs:
      run: echo "aofewaokfew"
    steps:
    - name: Echo output
      run: echo ${{ needs.prepare-image.outputs }}
      
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=docker.io\/kfysck\/devel" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "test=world" >> $GITHUB_OUTPUT      

# Testing Cache Only
  test-abc:
    runs-on: ubuntu-20.04
    needs: job1
    services:
      dtc:
        image: ${{needs.job1.outputs.output1}}
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
          
